### ISSUE TITLE
Wrong solution for chapter 10 exercise 1 and 2?

### ISSUE THREAD

**Issue by molok** [MostlyAdequate/mostly-adequate-guide#524]
for exercise 1 the solution is:

    const safeAdd = curry((a, b) => Maybe.of(add).ap(a).ap(b));

but using the `@mostly-adequate/support` library this doesn't work:

    safeAdd(1, 20);

returns this error:

    /home/user/tmp/mostly/node_modules/@mostly-adequate/support/index.js:414
    return this.isNothing ? this : f.map(this.$value);
                                     ^

    TypeError: f.map is not a function
    at Maybe.ap (/home/user/tmp/mostly/node_modules/@mostly-adequate/support/index.js:414:38)
    at curry (/home/user/tmp/mostly/src/index2.js:93:47)
    at $curry (/home/user/tmp/mostly/node_modules/@mostly-adequate/support/index.js:23:15)
    at Object.<anonymous> (/home/user/tmp/mostly/src/index2.js:94:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)

I would expect the solution to be 

    const safeAdd = curry((a, b) => Maybe.of(add).ap(Maybe.of(a)).ap(Maybe.of(b)));

unless I'm missing something

**Comment by KtorZ** [comment]
Hey! Your intuition is correct and your proposal would be legitimate if indeed `safeAdd` was working on numbers directly.

However, in the exercise, we give the following signature to `safeAdd`

```hs
safeAdd :: Maybe a -> Maybe b -> Maybe a
